version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard

  nodered:
    restart: always
    image: "nodered/node-red"
    ports:
      - "1881:1880"
    volumes:
      - nodered-data:/data

  mongodb:
    restart: always
    image: "mongo"
    ports:
      - "27017:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "your-mongo-username"
      MONGO_INITDB_ROOT_PASSWORD: "your-mongo-password"
    volumes:
      - mongodb-data:/data/db

networks:
  my_network:
    driver: bridge

volumes:
  mytb-data:
    external: true
  mytb-logs:
    external: true
  nodered-data:
    external: true
  mongodb-data:
    external: true
